# 插件在哪些世界里生效
enabled-worlds:
  - world

block:
  # 物理/邻接更新：比如沙子会掉落、红石受邻接触发、方块失去支撑等
  # 开启(true) = 拦截；关闭(false) = 不拦
  physics: true

  # 流体更新：水/岩浆流动、扩散
  fluids:  true

  # 生长/蔓延/生成：作物长高、草/菌丝/苔藓蔓延、树木生成等
  growth:  true

# 放行的材料（白名单，不受拦截）
# - 这些“方块本体”永远不过滤
# - 另外：若“某个方块上方一格”是白名单材料，这个“底座”也会被放行（白名单底座规则）
# - 下面默认放了常见红石组件，防止误拦造成红石断路
whitelist:
  - TORCH
  - REDSTONE_TORCH
  - REDSTONE_WIRE
  # - SUGAR_CANE       # 示例：想让甘蔗继续长就把作物本体加入白名单
  # - BAMBOO           # 示例：想让竹子继续长
  # - LEVER            # 示例：拉杆
  # - STONE_BUTTON     # 示例：按钮
  # - REPEATER         # 示例：中继器
  # - COMPARATOR       # 示例：比较器
  # - OBSERVER         # 示例：侦测器
  # - WALL_TORCH       # 示例：墙上火把（部分版本区分）

# 只拦这些材料（精确拦截）。留空 = 按上面的三大类型“全局拦截”
# 常见用法：
#   1）新手建议先留空[]，按类型总控，最省心
#   2）如果你只想拦“少数材料”，再开启下面的名单（例如只拦沙子/水/岩浆）
# 注意：
#   - 一旦这里不是空的[]，插件就“只会拦这里列出的材料”，其它材料即使属于开启的类型也不拦
materials-filter: []
  # 例子：只拦沙子掉落、水和岩浆流动，其它一律不拦
  # - SAND
  # - RED_SAND
  # - WATER
  # - LAVA
  # 例子：只拦草蔓延/菌丝蔓延（配合 block.growth: true 使用）
  # - GRASS_BLOCK
  # - MYCELIUM
  # - MOSS_BLOCK